apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviews-db-v1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/mysql
  claimRef:
    name: reviews-db-v1-pvc
    namespace: bookinfo
