apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratings-db-v1-pvc
  namespace: bookinfo
  labels:
    app: ratings-db
    version: v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
